config/routes.rb
RehactivePage::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  resources :contacts, only: [:new, :create, :show]
  resources :news, only: [:index, :show]
  resource :sitemap, only: :show

  get 'about' => 'static_pages#about', :as => :about_page
  get 'offer' => 'static_pages#offer', :as => :offer_page
  get 'map' => 'static_pages#map', :as => :map_page

  root :to => 'static_pages#home'
  namespace :admin do
    resources :news

    root to: "news#index"
  end
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/news.rb
class News < ActiveRecord::Base
  def short_body_without_html
    Nokogiri::HTML(self.content).css('body').text.squeeze(" \n")[0..100]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  layout "admin"
  before_filter :authenticate_user!

end

app/controllers/admin/news_controller.rb
class Admin::NewsController < Admin::AdminController

  def index
    @news = News.order("created_at desc").paginate(:per_page => per_page, :page => page)
  end

  def show
    @news = News.find(params[:id])
  end

  def edit
    @news = News.find(params[:id])
  end

  def new
    @news = News.new
    render :edit
  end

  def create
    @news = News.new(params[:news])

    respond_to do |format|
      format.html do
        if @news.save!
          redirect_to admin_news_path(@news)
        end
      end
    end
  end

  def update
    article_updated = false
    News.find(params[:id]).tap { |news|
      article_updated = news.update!(news_params)
    }

    respond_to do |format|
      format.html do
        if article_updated
          redirect_to(admin_news_path(params[:id]), notice: "Artykuł został pomyślnie zaktualizowany.")
        else
          render action: :edit
        end
      end
    end
  end

  def destroy
    @news = News.find(params[:id])
    @news.destroy
    redirect_to(admin_news_url)
  end

  private

  def news_params
    params.require(:news).permit(:title, :content, :content_short)
  end
end

app/controllers/admin_controller.rb
class Admin::AdminController < ApplicationController
  layout "admin"
  before_filter :authenticate_user!

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  private
  
  def page
    params[:page] || 1
  end

  def per_page
    params[:per_page] || 5
  end
  
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])

    if @contact.valid?
      UserMailer.contact(@contact).deliver
      render :show
    else
      render "new"
    end
  end

  def show
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController

  def index
    @news = News.order("created_at desc").paginate(:per_page => per_page, :page => page)
  end

  def show
    @news = News.find(params[:id])
  end
end

app/controllers/sitemaps_controller.rb
class SitemapsController < ApplicationController
  def show
    request.format = "xml" 
    @news = News.find(:all, :order => "updated_at DESC", :limit => 50000)
    headers["Content-Type"] = "text/xml"
    headers["Last-Modified"] = @news[0].updated_at.httpdate
    render layout: false
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  layout 'application'

  def home
  end

  def about
  end

  def offer
  end

  def map
  end

end

app/helpers/application_helper.rb
# encoding: utf-8
module ApplicationHelper

  def link_to_top
    label = image_tag('back_to_top_new.png') + 'Do góry'
    link_to label, '#top', :class => 'back-to-top'
  end
end

app/views/admin/news/_form.html.erb
<div class="news-form">
  <%= form_for [:admin, @news]  do |f| %>
    <div>
      <%= f.label :title, 'Tytuł:' %>
      <%= f.text_field :title %>
      <br/>
      <br/>
    </div>
    <div>
      <%= hidden_field_tag "news_id", params[:id] || "" %>
    </div>
    <div>
      <%= f.label :content_short, 'Podgląd Artykułu:' %>
      <br/>
      <br/>
      <%= f.cktext_area :content_short %>
    </div>

    <div>
      <%= f.label :body, 'Artykuł:' %>
      <br/>
      <br/>
      <%= f.cktext_area :content %>
    </div>

    <br/>
    <div>
      <%= f.submit :'data-disable-with' => 'Zapisuje...', class: 'btn btn-primary' %>
      <% if !@news.new_record?%>
        <%= link_to 'Usuń artykuł', admin_news_path(@news), method: :delete, data: {confirm: "Czy napewno chcesz usunac ten post?"}, class: 'btn btn-primary' %>
        <%= link_to "Powrót", admin_news_path(@news), class: 'btn btn-primary' %>
      <% else %>
        <%= link_to "Powrót", admin_root_path, class: 'btn btn-primary' %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/admin/news/_news.html.erb
<tr class="<%= klass %>">
  <td><%= link_to news.title, admin_news_path(news) %></td>
  <td class="date"><%= news.created_at %></td>
  <td class="content short-content"><%= news.short_body_without_html %></td>
</tr>

app/views/admin/news/edit.html.erb
<%= render "form" %>

app/views/admin/news/index.html.erb
<h1>Artykuły (<%= @news.count %>)</h1>
<%= link_to "Dodaj Artykuł", new_admin_news_path, class: 'btn btn-primary' %>
<br/>
<br/>

<table class="list">
  <thead>
    <tr>
      <td>Tytuł</td>
      <td>Data Utworzenia</td>
      <td class="short-content">Początek artykułu</td>
    </tr>
  </thead>
  <tbody>
    <% for news in @news do %>
      <%= render :partial => 'news', :locals => {:news => news, :klass => cycle('odd', 'even')} %>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td>Tytuł</td>
      <td>Data Utworzenia</td>
      <td class="short-content">Początek artykułu</td>
    </tr>
  </tfoot>
</table>

<div class='clear'></div>
<div class='pagination'>
  <%= will_paginate @news %>
</div>
<div class='clear'></div>

app/views/admin/news/show.html.erb
<div class="post">
	<div class="post-bgtop">
		<div class="post-bgbtm">
			<h2 class="title"><%= @news.title%></h2>
			<p class="byline">Dodano <%= @news.created_at %></p>
			<div class="entry">
				<p><%= @news.content.html_safe %></p>
			</div>
		</div>
	</div>
</div>
<br/>
<br/>
<div class="actions">
  <%= link_to "Edytuj", edit_admin_news_path(@news), class: 'btn btn-primary' %>
  <%= link_to "Cofnij", admin_root_path, class: 'btn btn-primary'  %>
</div>

app/views/contacts/new.html.erb
<% content_for :header do %>
  <%= render :partial => "shared/header_menu" %>
<%end%>

<% content_for :meta_header do %>
  <title>Rehabilitacja Białystok - Rehactive kontakt</title>
<%end%>

<% content_for :right_sidebar do %>
  <%= render :partial => "shared/right_sidebar" %>
<%end%>

<% content_for :head do %>
  <meta name="description" content="Skontaktuj się ze mną."/>
<% end %>

<div class="post">
	<div class="post-bgtop">
		<div class="post-bgbtm">
			<h2 class="title">Kontakt</h2><br/>
      <% unless @contact.errors.empty? %>
        <div class="alert">
          <h2>Errors occured</h2>
          <ul>
            <% @contact.errors.full_messages.each do |msg| %>
              <li>
              <%= msg %>
              </li>
            <% end %>
          </ul>
        </div>
      <% end %>
			<div class="entry">
        <div id="contact" class ="common-div-form">
          <%= form_for @contact do |f| %>
          <table>
            <tr>
              <td><%= f.label :name, 'Imię, Nazwisko/Nazwa firmy:' %></td>
            </tr>
            <tr>
              <td><%= f.text_field :name %></td>
            </tr>
            <tr>
              <td><%= f.label :email, 'Email:' %></td>
            </tr>
            <tr>
              <td><%= f.text_field :email %></td>
            </tr>
            <tr>
              <td><%= f.label :content, 'Treść:', :class=>"news-form-content" %></td>
            </tr>
              <td><%= f.text_area :content, :rows => 13, :cols => 42 %><br /></td>
            </tr>
            <tr>
              <td>
                <%= f.submit "Wyślij", class:"user-submit" %>
              </td>
            </tr>
          </table>
        <% end %>
        </div>
			</div>
		</div>
	</div>
</div>

app/views/contacts/show.html.erb
<% content_for :header do %>
  <%= render :partial => "shared/header_menu" %>
<%end%>

<% content_for :right_sidebar do %>
  <%= render :partial => "shared/right_sidebar" %>
<%end%>

<% content_for :meta_header do %>
  <title>Rehabilitacja Białystok - Rehactive dziękuję za kontakt</title>
<%end%>

<% content_for :head do %>
  <meta name="description" content="Thanks for your message! - Shopikon."/>
<% end %>
<h3 id="thanks">Dziękuję za kontakt.</h3>

app/views/layouts/_header.html.erb
<header>
  <div class="menu">
    <div class="menu-container">
      <%= link_to "News", admin_root_path %>
    </div>
  </div>

  <div class="clearfix"></div>
  </div>
</header>

app/views/layouts/admin.html.erb
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <%= csrf_meta_tag %>

  <!-- Mobile viewport optimized: j.mp/bplateviewport -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= yield :meta_header %>
  <!-- Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons -->

  <!-- CSS: implied media="all" -->
  <%= stylesheet_link_tag "admin" %>

  <%= javascript_include_tag "application" %>
  <%= yield :head %>
</head>

<body class="<%= controller_name %>-controller <%= action_name %>-action">
  <%= render 'layouts/header' %>

  <div class='container_24'>
    <div class='grid_24'>
      <div id='flash-messages'>
        <% if notice %>
          <p class="notice"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert"><%= alert %></p>
        <% end %>
      </div>
    </div>
  </div>

  <div id='admin-content'>
    <div class='container_24'>
      <div class='grid_24'>
        <div class='top-left-edge'>
          <%= yield %>
        </div>
      </div>
    </div>
    <div class='clear'></div>
  </div>

  <%= yield :javascripts %></body>
</html>

app/views/layouts/application.html.erb
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <%= csrf_meta_tag %>
  <!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame
       Remove this if you use the .htaccess -->
  <!--[if ie]>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <script>
      document.createElement('header');
      document.createElement('footer');
    </script>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <link rel="shortcut icon" href="<%= asset_path 'rehactive.png' %>" />
  <meta name="description" content="Gabinet rehabilitacji Joanna Bieniek-Sobolewska" />
  <meta name="author" content="www.rehactive.pl" />
  <meta property="og:title" content="Rehactive"/>
  <meta property="og:type" content="website"/>
  <meta property="og:description" content="Gabinet Rehabilitacji Joanna Bieniek-Sobolewska. Rehabilitacja Białystok. Gabinet rehabilitacji Białystok. Zajmujemy się niwelowaniem problemów ze stawami, dyskopatią, rwą kulszową, wadami postawy, urazami, srkęceniami i innymi dolegliwościami."/>
  <meta content="<%= asset_path 'fblogo.png' %>" property="og:image" />
  <meta content="http://www.rehactive.pl" property="og:url" />
  <meta property="og:site_name" content="www.rehactive.pl"/>
  <meta property="fb:app_id" content="221006548001774"/>
  <meta name="google-site-verification" content="2AfSWevjUMKBKc4dVBOFYc229pyjEhtIzrGxrR8P-4Q" />
  <!-- Mobile viewport optimized: j.mp/bplateviewport -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= yield :meta_header %>
  <!-- Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons -->

  <!-- CSS: implied media="all" -->
  <%= stylesheet_link_tag "application" %>
  
  <%= javascript_include_tag "application" %>
  <%= yield :head %>
  <script type="text/javascript">
    var apiKey = '';
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', apiKey]);
    _gaq.push(['_setDomainName', 'sloogd.com']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>
  <%= yield :scripts %>
</head>

<body class="<%= controller_name %>-controller <%= action_name %>-action">
  <a id="top"></a>
  <header>
    <section>
      <%= yield :header %>
    </section>
  </header>

  <section id="wrapper">
    <section class="main">
      <div id="content">
        <%= yield %> <!--! end of #container -->
      </div>
      <%= yield :right_sidebar %>
    </section>
  </section>

  <%= render partial: "shared/footer" %>

</body>
</html>

app/views/news/index.html.erb
<% content_for :header do %>
  <%= render :partial => "shared/header_menu" %>
<%end%>

<% content_for :meta_header do %>
  <title>Rehabilitacja Białystok - Rehactive aktualności</title>
<%end%>

<% content_for :right_sidebar do %>
  <%= render :partial => "shared/right_sidebar" %>
<%end%>

<% content_for :head do %>
  <meta name="description" content="Aktualności firmy Rehactive"/>
<% end %>

<% @news.each do |n| %>
  <div class="post">
		<div class="post-bgtop">
			<div class="post-bgbtm">
				<h2 class="title"><a href="<%= news_path(n)%>"><%= n.title%> </a></h2>
				<p class="byline">Dodano <%= n.created_at %></p>
				<div class="entry">
					<p><%= n.content_short.html_safe %></p>
				</div>
				<div class="meta">
					<p><a href="<%= news_path(n)%>" class="news-show-link">Szczegóły</a></p>
				</div>
			</div>
		</div>
	</div>
<% end %>

<% unless @news.empty? -%>
  <%= link_to_top %>
  <%= will_paginate @news %>
<% end -%>

app/views/news/show.html.erb
<% content_for :header do %>
  <%= render :partial => "shared/header_menu" %>
<%end%>

<% content_for :meta_header do %>
  <title>Rehabilitacja Białystok <%= 'Rehactive - ' + @news.title%></title>
<%end%>

<% content_for :right_sidebar do %>
  <%= render :partial => "shared/right_sidebar" %>
<%end%>

<% content_for :head do %>
  <meta name="description" content="<%= 'Rehactive - ' + @news.title%>"/>
<% end %>

<div class="post">
	<div class="post-bgtop">
		<div class="post-bgbtm">
			<h2 class="title"><%= @news.title%></h2>
			<p class="byline">Dodano <%= @news.created_at %></p>
			<div class="entry">
				<p><%= @news.content.html_safe %></p>
			</div>
		</div>
	</div>
</div>

app/views/shared/_footer.html.erb
<footer>
  <section>
    <p id="legal">All Rights Reserved. Copyright © 2011. --- REHACTIVE</p>
    <p>Rehabilitacja Białystok - Gabinet rehabilitacji Rehactive</p>
    <p id="links">
      <%= link_to "Aktualności", news_index_path %>
      <%= link_to "Oferta", offer_page_path %>
      <%= link_to "O mnie", about_page_path %>
      <%= link_to "Kontakt", new_contact_path %>
    </p>
  </section>
</footer>

app/views/shared/_header_menu.html.erb
<div id="logo">
	<%= link_to image_tag("logo.png"), root_path %>
</div>
<div id="menu">
  <ul>
    <li id="news" class="<%= 'active' if params[:controller]=='news'%>">
      <%= link_to "Aktualności", news_index_path %>
    </li>
    <li id="offer" class="<%= 'active' if params[:action]=='offer'%>">
      <%= link_to "Oferta", offer_page_path %>
    </li>
    <li id="about" class="<%= 'active' if params[:action]=='about'%>">
      <%= link_to "O mnie", about_page_path %>
    </li>
    <li id="contact" class="<%= 'active' if params[:action]=='contact'%>">
      <%= link_to "Kontakt", new_contact_path %>
    </li>
  </ul>
</div>

app/views/shared/_right_sidebar.html.erb
<div id="sidebar">
	<div id="sidebar-bgtop">
		<div id="sidebar-bgbtm">
			<ul>
				<li>
					<h2>Gabinet Rehabilitacji</h2>
          <p>ul.Radzymińska 2A lok. U2a</p>
				</li>
				<li>
					<h2>Godziny otwarcia:</h2>
          <p>Dostosowane do potrzeb pacjenta</p>
				</li>
				<li>
					<h2>Fizjoterapeuta</h2>
					<p class="bold">mgr Joanna Bieniek-Sobolewska</p>
          <p>tel.  515 479 644</p>
				</li>
				<li>
					<h2>Mapa dojazdu</h2>
          <div id="gmaps">
			      <%= link_to image_tag("mapka.png"), map_page_path %>
			    </div>
				</li>
				<li class="share">
				  <h2>Poleć innym</h2>
          <p>Gabinet rehabilitacji Rehactive w Białymstoku</p>
				  <!-- AddThis Button BEGIN -->
          <div class="addthis_toolbox addthis_default_style addthis_32x32_style" addthis:url="www.rehactive.pl">
            <a class="addthis_button_facebook"></a>
            <a class="addthis_button_twitter"></a>
          </div>
          <script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=xa-4f9d4582030b1b6b"></script>
          <!-- AddThis Button END -->
				</li>
			</ul>
		</div>
	</div>
</div>

app/views/static_pages/about.html.erb
<% content_for :header do %>
  <%= render :partial => "shared/header_menu" %>
<%end%>

<% content_for :right_sidebar do %>
  <%= render :partial => "shared/right_sidebar" %>
<%end%>

<% content_for :meta_header do %>
  <title>Rehabilitacja Białystok - Rehactive o mnie</title>
<%end%>

<% content_for :head do %>
  <meta name="description" content="Rehactive - informacje o mnie"/>
<% end %>

<div class="post">
	<div class="post-bgtop">
		<div class="post-bgbtm">
			<h2 class="title">mgr Joanna Bieniek-Sobolewska</h2><br/>
			<div class="entry about">
			  <%= image_tag("https://s3.amazonaws.com/rehactive/gabinet/IMG_1119_small.JPG")%>
				<p>Jestem absolwentką Uniwersytetu Medycznego w Łodzi. Moja przygoda z fizjoterapią zaczęła się jeszcze przed studiami. Miałam możliwość przyglądania się pracy innych specjalistów w tej dziedzinie. Już wtedy stwierdziłam, że Fizjoterapia jest tym, co chcę robić w przyszłości.</p>
				<p>Jest to cudowny zawód dający niesamowitą satysfakcję. Czy jest coś piękniejszczego niż zadowolony pacjent, który odzyskał sprawność, pozbył się dolegliwości bólowych i wrócił do pełnej sprawności, normalnego życia?</p>
				<p>Dzięki specjalistycznym kursom mam możliwość pracy nowoczesnymi metodami fizjoterapeutycznymi, takimi jak: metoda McKenziego, Terapia Manualna wg Mulligan Concept, Kinesiology Taping, Taping Sportowy, Terapia tkanek miękkich wg E. Wilsona i masaż.</p>
				<p>Dodatkowo swoją wiedzę zgłębiałam na szkoleniach specjalistycznych z zakresu rehabilitacji stawu barkowego i kolanowego.</p>
				<p>Specjalizuję się w rehabilitacji:</p>
				<ul>
				  <li>neurologicznej w zakresie bólów kręgosłupa (dyskopatia, rwa kulszowa, rwa ramienna, korzonki, mrowienie, drętwienie kończyn, ból promieniujący do kończyn, podbrzusza, pachwin, bóle i zawroty głowy)</li>
				  <li>ortopedycznej (staw kolanowy, barkowy, biodrowy, łokieć tenisisty i golfisty, po urazach sportowych, np. skręceniach stawu, cieśń nadgarstka, ostrogi piętowe, nieoperacyjne leczenie halluxów)</li>
				  <li>po zabiegach operacyjnych, np. artroskopii</li>
				  <li>korekcji wad postawy (terapia indywidualna oraz gimnastyka korekcyjna w przedszkolach)</li>
				  <li>masażu – obrzęki limfatyczne</li>
				</ul>
			</div>
		</div>
	</div>
</div>

app/views/static_pages/contact.html.erb
<% content_for :header do %>
  <%= render :partial => "shared/header_menu" %>
<%end%>

<% content_for :right_sidebar do %>
  <%= render :partial => "shared/right_sidebar" %>
<%end%>

app/views/static_pages/home.html.erb
<% content_for :header do %>
  <%= render :partial => "shared/header_menu" %>
<%end%>

<% content_for :right_sidebar do %>
  <%= render :partial => "shared/right_sidebar" %>
<%end%>

<% content_for :meta_header do %>
  <title>Rehabilitacja Białystok - Rehactive Twoja wizyta</title>
<%end%>
<% content_for :head do %>
  <meta name="description" content="Gabinet Rehabilitacji Rehactive"/>
<% end %>

<div id="gallery-bg">
	<div id="gallery-bgtop">
		<div id="gallery-bgbtm">
      <ul id="myGallery">
	      <li><%= image_tag("https://s3.amazonaws.com/rehactive/gabinet/IMG_1110_small.JPG") %></li>
	      <li><%= image_tag("https://s3.amazonaws.com/rehactive/gabinet/DSC05108_small.JPG") %></li>
	      <li><%= image_tag("https://s3.amazonaws.com/rehactive/gabinet/IMG_1079_small.JPG") %></li>
	      <li><%= image_tag("https://s3.amazonaws.com/rehactive/gabinet/IMG_0982_small.JPG") %></li>
      </ul>
		</div>
	</div>
</div>

<div class="post">
	<div class="post-bgtop">
		<div class="post-bgbtm">
			<h2 class="title">Twoja wizyta</h2><br/>
			<div class="entry">
				<p>Podczas terapii zostanie przeprowadzony szczegółowy wywiad z pacjentem w celu poznania objawów z jakimi zgłosił się pacjent, dotychczasowego leczenie, chorób towarzyszących i przyjmowanych leków, w celu ustalenia przyczyny dolegliwości.</p>
        <p>Poznanie przyczyny choroby pozwala ustalić skuteczny program rehabilitacji, dobrać odpowiednie metody w celu jak najszybszego usprawnienia pacjenta.</p>
			</div>
		</div>
	</div>
</div>

app/views/static_pages/map.html.erb
<% content_for :header do %>
  <%= render :partial => "shared/header_menu" %>
<%end%>

<% content_for :meta_header do %>
  <title>Rehabilitacja Białystok - Rehactive mapa dojazdu</title>
<%end%>


<% content_for :head do %>
  <meta name="description" content="Rehactive - mapa dojazdu"/>
<% end %>

<div id="map-bg">
	<div id="map-bgtop">
		<div id="map-bgbtm">
      <% @map = '[{"lng":"23.155302","lat":"53.146046"}]'%>
      <%= gmaps("markers" => {"data" => @map}, "map_options" => {"processing" => "json", "auto_zoom" => false, "zoom" => 16}) %>
		</div>
	</div>
</div>

app/views/user_mailes/contact.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="description" content="Contact us form - Shopikon."/>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
  </head>
  <body>
    <h1><%= @contact.name %> skontaktował się z Tobą</h1>

    <h2>Treść wiadomości:</h2>
    <p><%= @contact.message %></p>

    <h2>E-mail:</h2>
    <p><%= @contact.email %></p>
    
    <h2>Treść:</h2>
    <p><%= @contact.content %></p>

  </body>
</html>